# 예외
## 예외
* Kotlin에서 예외를 발생시키려면 throw 키워드를 사용해야하며, 객체 생성과 마찬가지로 new 키워드는 사용하지 않습니다.
~~~kotlin
fun checkAge(age: Int) {
    if(age < 0) {
        throw IllegalArgumentException
            ("Invalid age: $age")
    }
}
~~~
* 예외를 처리하기 위해서는 Java와 동일하게  try-catch 및 finally문을 사용하면 됩니다. Kotlin에서 try-catch문은 값을 반환할 수 있습니다.
~~~kotlin
// try-catch 문에서 바로 값을 받습니다.
val valid : Boolean = try {
    // 예외를 발생시킬 수 있는 코드들

    // 예외가 발생하지 않았을 경우 true를 반환
    true
} catch (e: Exception) {
    // 예외가 발생했을 떄 수행할 동작

    // false 반환
    false
} finally {
    // 예외 발생 여부와 상관없이 수행할 동작

}
~~~
* Kotlin은 Checked exception을 따로 검사하지 않습니다. 대부분의 예외를 Java에서 처럼 try-catch문으로 감싸지 않고 선택적으로 사용할 수 있습니다.
~~~kotlin
fun readFromJson(fileName: String): String {
    // IOException을 발생시킬 수 있는 코드

}

fun process() {
    // try-catch문을 사용하지 않아도 됩니다.
    val json: String =
    readFromJson("foo.json")
}
~~~